[package]
name = "database"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7.3", features = ["runtime-tokio-native-tls", "postgres", "sqlite", "uuid", "time"] }
config.workspace = true
anyhow.workspace = true