[package]
name = "authserver"
version = "0.0.0"
description = "TBD"

authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
tokio.workspace = true
wow_login_messages.workspace = true
wow_srp.workspace = true